### ISSUE TITLE
Laravel 7.4 compatibility

### ISSUE THREAD

**Issue by SuryaVanLierde** [koenhoeijmakers/laravel-translatable#12]
`Declaration of KoenHoeijmakers\LaravelTranslatable\HasTranslations::resolveRouteBinding($value) must be compatible with Illuminate\Database\Eloquent\Model::resolveRouteBinding($value, $field = NULL)`

I'm not sure if this can be updated without breaking backwards compatibility

**Comment by koenhoeijmakers** [comment]
Thanks for reporting this, seems that the package never properly had Laravel ^7.0 support, i'll tag `0.6` with the fix.
